# Generated by Django 5.0.1 on 2025-04-16 20:27
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags'),
    ]

    operations = [
       TrigramExtension()
    ]
